### ISSUE TITLE
Swamp's wooden planks cause the boss to never get you. 

### ISSUE THREAD

**Issue by TheCrocTM** [KitRifty/slender-fortress#10]
I jumped on the wooden planks in front of the house on the map Slender_Swamp, and the boss will never hit you (unless it's a range boss) until you get out of the corner of the wooden planks.
http://imgur.com/FqHMeve

Hope to get fixed soon.
-The Croc™

**Comment by Kenzzer** [comment]
It's nav mesh bug not related to the mod. A nav editing can fix it, I recommand you to report this bug next time to servers owner. And I reported it too some days ago, and it's now fixed.

**Comment by Glubbable** [comment]
It's already been fixed.
