### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Draakoor** [KitRifty/slender-fortress#11]
I dont know why is it not working.

Pls test it yourself.

I dont know if its the gamedata or the complete plugin

**Comment by Glubbable** [comment]
Check your sourcemod error logs.

**Comment by Draakoor** [comment]
I dont get any errors.

Sm version:
 SourceMod Version Information:
    SourceMod Version: 1.7.3-dev+5240
    SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5240)
    SourcePawn API: v1 = 4, v2 = 6
    Compiled on: Sep 10 2015 16:59:08
    Built from: https://github.com/alliedmodders/sourcemod/commit/cb3da52
    Build ID: 5240:cb3da52
    http://www.sourcemod.net/

Plugins:

  01 "Client Preferences" (1.7.3-dev+5240) by AlliedModders LLC
  02 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
  03 "[TF2] Have Some Ballz" (1.0) by DarthNinja
  04 "[TF2] Building Hats" (1.8) by Pelipoika
  05 "Boom Headshot Remake!" (1.0.0) by DarthNinja
  06 "Sound Commands" (1.7.3-dev+5240) by AlliedModders LLC
  07 "Basic Votes" (1.7.3-dev+5240) by AlliedModders LLC
  08 "The Amplifier" (2.4) by RainBolt Dash (plugin); Jumento M.D. (idea & model); Naris and FlaminSarge (helpers)
  09 "[TF2] MakeMeInvisible" (1.3.4) by bobomaster
  10 "Observer Point" (1.0.100) by <eVa>Dog
  11 "[TF2] Pedobear NPC" (2.0.1) by Oshizu / Sena? ?
  12 "Evil Admin - Vision" (1.0.106) by <eVa>Dog
  13 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
  14 "SP-Readable Navigation Mesh Test" (1.0.1) by KitRifty
  15 "[TF2] TF2Attributes" (1.2.1) by FlaminSarge
  16 "Fun Commands X" (2.4) by Spazman0 and Arg!
  17 "Anti-Flood" (1.7.3-dev+5240) by AlliedModders LLC
  18 "[TF2] Thirdperson" (2.1.0) by DarthNinja
  19 "[TF2] Boss Spawns" (1.0.8) by abrandnewday, reworked by Keith Warren (Jack of Designs)
  20 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
  21 "[TF2] Shred Alert Tauntkill" (1.0.1) by FlaminSarge
  22 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
  23 "[TF2] Pyro Airblast Jump" (1.2.2) by Leonardo
  24 "Admin all spec" (1.0.2) by Dr!fter
  25 "False Messages" (3.1) by Jindo
  26 "Basic Info Triggers" (1.7.3-dev+5240) by AlliedModders LLC
  27 "Evil Admin - Rocket" (1.0.110) by <eVa>Dog
  28 "Quake Sounds v3" (3.4.2) by Spartan_C001
  29 "Say Sounds (including Hybrid Edition)" (4.0.8) by Hell Phoenix|Naris|FernFerret|Uberman|psychonic|edgecom|woody|Miraculix|gH0sTy
  30 "BuildingsSpawner" (1.0.3) by X3Mano
  31 "Updater" (1.2.2) by GoD-Tony
  32 "Basic Chat" (1.7.3-dev+5240) by AlliedModders LLC
  33 "Basic Commands" (1.7.3-dev+5240) by AlliedModders LLC
  34 "Basic Comm Control" (1.7.3-dev+5240) by AlliedModders LLC
  35 "Horsemann Health Bar" (1.3.2) by Powerlord
  36 "BROFIST" (1.2.1) by MasterOfTheXP
  37 "[TF2] Set Player Class" (1.0.1) by DarthNinja
  38 "Spray Tracer" (5.8a) by Nican132, CptMoore, Lebson506th
  39 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee
  40 "Fun Commands" (1.7.3-dev+5240) by AlliedModders LLC
  41 "Connect Announce" (1.6) by Arg!
  42 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  43 "Evil Admin - Health" (1.0.104) by <eVa>Dog
  44 "SourceBans" (1.4.11) by SourceBans Development Team
  45 "Fart" (1.0.102) by <eVa>Dog
  46 "[TF2] Be The Ghost" (1.1.3) by Leonardo
  47 "Evil Admin - Glow" (1.0.107) by <eVa>Dog
  48 "[TF2] Set Speed" (1.1) by ChauffeR
  49 "[Any] Deluxe Godmode" (2.3.1) by DarthNinja
  50 "Be the Robot" (1.3) by MasterOfTheXP
  51 "Jarate Teammates" (1.05) by simoneaolson
  52 "[TF2] Doomsday nuke" (1.2) by Pelipoika
  53 "Slender Fortress" (0.2.6-git136) by KitRifty
  54 "[TF2] Respawn Player" (1.0) by Starman2098
  55 "Admin File Reader" (1.7.3-dev+5240) by AlliedModders LLC
  56 "[TF2] Colored Engineer Buildings" (1.1) by Oshizu
  57 "Advertisements" (0.6) by Tsunami
  58 "[TF2] Soldier Eyerockets!" (1.0.0) by Oshizu
  59 "Fun Votes" (1.7.3-dev+5240) by AlliedModders LLC
  60 "Fun Cvars" (1.0.0) by Wild1234
  61 "Player-Teleport by Dr. HyperKiLLeR" (1.2.0.0) by Dr. HyperKiLLeR
  62 "Reserved Slots" (1.7.3-dev+5240) by AlliedModders LLC
  63 "Evil Admin - Pimp Slap" (1.0.102) by <eVa>Dog
  64 "SourcePawn Navigation Mesh Parser" (1.0.3) by KitRifty
  65 "Set Metal" (1.0.1) by Tylerst
  66 "Welcome Sound" (0.0.1) by R-Hehl
  67 "Admin Help" (1.7.3-dev+5240) by AlliedModders LLC
  68 "Evil Admin - Beam" (1.0.100) by <eVa>Dog
  69 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
  70 "Screen Overlays" (1.0) by ReFlexPoison
  71 "[TF2] Have Some Piss" (1.0) by DarthNinja
  72 "[DEV] TF2ItemsInfo" (1.9.1) by Leonardo | Maintained by ChauffeR
  73 "Admin Player Grabber" (1.0.1) by Friagram
  74 "Anti Stuck" (1.00) by muso.sk
  75 "Nextmap" (1.7.3-dev+5240) by AlliedModders LLC
  76 "[TF2Items] Give Weapon" (3.14159) by FlaminSarge (orig by asherkin)
  77 "Admin List" (1.2) by Fredd
  78 "Evil Admin - Trails" (1.0.104) by <eVa>Dog
  79 "Fish Humiliation" (0.2) by retsam
  80 "Player Commands" (1.7.3-dev+5240) by AlliedModders LLC
  81 "Admin Menu" (1.7.3-dev+5240) by AlliedModders LLC
  82 "[TF2] Heavy Sprint" (1.0) by noodleboy347
  83 "TF Force Holidays" (1.10.1) by Powerlord
  84 "Gamevoting" (1.5b) by Neatek.ru 

SM extensions:

[01] Automatic Updater (1.7.3-dev+5240): Updates SourceMod gamedata files
[02] Webternet (1.7.3-dev+5240): Extension for interacting with URLs
[03] TF2Items (1.6.1): TF2 Item Modifier
[04] TF2 Tools (1.7.3-dev+5240): TF2 extended functionality
[05] BinTools (1.7.3-dev+5240): Low-level C/C++ Calling API
[06] SDK Hooks (1.7.3-dev+5240): Source SDK Hooks
[07] SDK Tools (1.7.3-dev+5240): Source SDK Tools
[08] Client Preferences (1.7.3-dev+5240): Saves client preference settings
[09] SQLite (1.7.3-dev+5240): SQLite Driver
[10] Top Menus (1.7.3-dev+5240): Creates sorted nested menus
[11] Regex (1.7.3-dev+5240): Provides regex natives for plugins
[12] DHooks (2.0.3): Dynamic Hooks
[13] Sound Info Library (1.0): Access information of sound files
[14] SteamTools (0.9.1+7202836): SteamWorks for SourceMod.
[15] <FAILED> file "SteamWorks.ext.so": /home/steam/gameserver/tf2sl/tf/addons/sourcemod/extensions/SteamWorks.ext.so: cannot open shared object file: No such file or directory
[16] cURL Extension (1.3.0.0): cURL Extension
[17] Socket (3.0.1): Socket extension for SourceMod
[18] GeoIP (1.7.3-dev+5240): Geographical IP information
[19] GeoIPCity (1.1.1): Geographical IP information
[20] MySQL-DBI (1.7.3-dev+5240): MySQL driver implementation for DBI

Please help me

**Comment by Glubbable** [comment]
Please, look at addons/sourcemod/logs as that is where any errors are printed to whenever something goes wrong.

**Comment by Draakoor** [comment]
I dont get any errors and the log is not created.

The server crashes after he tries to strip my weapons to melee.
Pls check the gamedata.

Sourcemod log:
L 09/14/2015 - 12:29:38: SourceMod log file session started (file "L20150914.log") (Version "1.7.3-dev+5240")
L 09/14/2015 - 12:29:38: -------- Mapchange to slender_cellars_b4a --------
L 09/14/2015 - 12:29:38: [TF2ITEMS] "GiveNamedItem" offset = 478
L 09/14/2015 - 12:29:38: [GEOIP] GeoIP database info: GEO-106FREE 20150407 Build 1 Copyright (c) 2015 MaxMind Inc All Rights Reserved
L 09/14/2015 - 12:29:38: [GEOIPCITY] GeoIPCity database info: GEO-533LITE 20141007 Build 1 Copyright (c) 2014 MaxMind Inc All Rights Reserved
L 09/14/2015 - 12:29:38: [HaveSomeBallz.smx] Ballsballsballsballsballsballsballsballsballsballs.
L 09/14/2015 - 12:29:38: [funcommandsX.smx] Game detected as Team Fortress 2: Source (GAME_TF2)
L 09/14/2015 - 12:29:38: [saysounds.smx] [Say Sounds] Detected Team Fortress 2
L 09/14/2015 - 12:29:40: [HaveSomePiss.smx] God save the piss!
L 09/14/2015 - 12:29:47: [tf2items_giveweapon.smx] [TF2Items GiveWeapon] TF2ItemsInfo loaded 394 items.
L 09/14/2015 - 12:29:47: [tf2items_giveweapon.smx] [TF2Items GiveWeapon] TF2ItemsInfo loaded 394 items.
L 09/14/2015 - 12:29:56: [navmesh.smx] Found .NAV file in maps\slender_cellars_b4a.nav
L 09/14/2015 - 12:29:56: [navmesh.smx] Is mesh analyzed: 1
L 09/14/2015 - 12:29:56: [navmesh.smx] Nav version: 16; SubVersion: 2 (v10+); BSPSize: 10666660; MagicNumber: -17958194
L 09/14/2015 - 12:29:56: [navmesh.smx] Place count: 0
L 09/14/2015 - 12:29:56: [navmesh.smx] Has unnamed areas: true
L 09/14/2015 - 12:29:56: [navmesh.smx] Area count: 1866
L 09/14/2015 - 12:29:56: [navmesh.smx] All nav areas parsed into the grid!
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2041_viewmodel: Preparing models/weapons/c_models/c_v_ludmila/c_v_ludmila.mdl
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2058_model: cannot find valid model models/custom/weapons/antehgen/urinejar.mdl, skipping
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2058_viewmodel: cannot find valid model models/custom/weapons/antehgen/urinejar.mdl, skipping
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.mdl
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.phy
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.vvd
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.dx90.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.dx80.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing models/advancedweaponiser/w_sickle_sniper.sw.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing materials/advancedweaponiser/sickle_sniper/scythe.vmt
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_model: Preparing materials/advancedweaponiser/sickle_sniper/scythe.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.mdl
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.phy
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.vvd
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.dx90.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.dx80.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing models/advancedweaponiser/w_sickle_sniper.sw.vtx
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing materials/advancedweaponiser/sickle_sniper/scythe.vmt
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2171_viewmodel: Preparing materials/advancedweaponiser/sickle_sniper/scythe.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_model: Preparing models/custom/weapons/rebelscurse/c_wrench_v2.mdl
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_model: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vmt
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_model: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_model: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_viewmodel: Preparing models/custom/weapons/rebelscurse/c_wrench_v2.mdl
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_viewmodel: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vmt
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_viewmodel: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2197_viewmodel: Preparing materials/models/custom/weapons/rebelscurse/rebels_curse.vtf
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2228_model: cannot find valid model models/advancedweaponiser/fbomb/c_fbomb.mdl, skipping
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]2228_viewmodel: cannot find valid model models/advancedweaponiser/fbomb/c_fbomb.mdl, skipping
L 09/14/2015 - 12:29:56: [tf2items_giveweapon.smx] [TF2Items GiveWeapon]5142_viewmodel: cannot find valid model models/custom/weapons/goldslinger/c_engineer_gunslinger.mdl, skipping
L 09/14/2015 - 12:29:58: [buildinghats.smx] [Building Hats] Executing configuration file addons/sourcemod/configs/buildinghats.cfg
L 09/14/2015 - 12:29:58: [mapchooser_extended.smx] Loaded map list for tf.
L 09/14/2015 - 12:29:58: [sf2.smx] Loaded special rounds file!
L 09/14/2015 - 13:08:32: SourceMod log file session started (file "L20150914.log") (Version "1.7.3-dev+5240")
L 09/14/2015 - 13:08:32: -------- Mapchange to slender_cellars_b4a --------
L 09/14/2015 - 13:08:32: [TF2ITEMS] "GiveNamedItem" offset = 478
L 09/14/2015 - 13:08:32: [GEOIP] GeoIP database info: GEO-106FREE 20150407 Build 1 Copyright (c) 2015 MaxMind Inc All Rights Reserved
L 09/14/2015 - 13:08:32: [GEOIPCITY] GeoIPCity database info: GEO-533LITE 20141007 Build 1 Copyright (c) 2014 MaxMind Inc All Rights Reserved
L 09/14/2015 - 13:08:32: [HaveSomeBallz.smx] Ballsballsballsballsballsballsballsballsballsballs.
L 09/14/2015 - 13:08:33: [funcommandsX.smx] Game detected as Team Fortress 2: Source (GAME_TF2)
L 09/14/2015 - 13:08:33: [saysounds.smx] [Say Sounds] Detected Team Fortress 2
L 09/14/2015 - 13:08:34: [HaveSomePiss.smx] God save the piss!

SL2 log:
L 09/14/2015 - 12:24:19: [sf2.smx] Found sf2_escape_time_limit entity, set escape time limit to 85
L 09/14/2015 - 12:24:19: [sf2.smx] Found sf2_time_gain_from_page entity, set time gain to 10
L 09/14/2015 - 12:24:19: [sf2.smx] Found sf2_time_limit entity, set time limit to 220
L 09/14/2015 - 12:24:19: [sf2.smx] Found sf2_maxplayers entity, set maxplayers to 8
L 09/14/2015 - 12:24:19: [sf2.smx] Found sf2_boss_override entity, set boss profile override to grunt
L 09/14/2015 - 12:24:19: [sf2.smx] Loaded page music ranges successfully!
L 09/14/2015 - 12:29:58: [sf2.smx] -------- Mapchange to slender_cellars_b4a -------
L 09/14/2015 - 12:29:58: [sf2.smx] Loading boss profiles from file addons/sourcemod/configs/sf2/profiles.cfg...
L 09/14/2015 - 12:29:58: [sf2.smx] slenderman...
L 09/14/2015 - 12:29:58: [sf2.smx] rake...
L 09/14/2015 - 12:29:58: [sf2.smx] weepingangel...
L 09/14/2015 - 12:29:58: [sf2.smx] Loaded 3 boss profile(s) from file!
L 09/14/2015 - 12:29:58: [sf2.smx] Reloaded restricted weapons configuration file successfully
L 09/14/2015 - 13:08:10: [sf2.smx] Found sf2_escape_time_limit entity, set escape time limit to 85
L 09/14/2015 - 13:08:10: [sf2.smx] Found sf2_time_gain_from_page entity, set time gain to 10
L 09/14/2015 - 13:08:10: [sf2.smx] Found sf2_time_limit entity, set time limit to 220
L 09/14/2015 - 13:08:10: [sf2.smx] Found sf2_maxplayers entity, set maxplayers to 8
L 09/14/2015 - 13:08:10: [sf2.smx] Found sf2_boss_override entity, set boss profile override to grunt
L 09/14/2015 - 13:08:10: [sf2.smx] Loaded page music ranges successfully!

**Comment by Glubbable** [comment]
There is nothing in the gamedata that relates to weapon restriction.
This is a plugin conflict you are having with something that touches players weapons.

**Comment by Draakoor** [comment]
I posted my plugin list already, pls help me

**Comment by Glubbable** [comment]
A plugin list or a standard sourcemod log does not help.

"The server crashes after he tries to strip my weapons to melee."
This is a plugin conflict you are having with something that touches players weapons. Unload all of your custom plugins except for the ones that are needed. You own the server, not me.

**Comment by Draakoor** [comment]
Thx.
I removed some of my default serverplugins and now it works.

I only have two question: Is it normal that the slendermans head is purple when I see the death/kill overlay?
Is there a way to setup a config for special bosses, I'd like to use the FNAF but I don't want them if there are only 2 players?

All files are on my gameserver and web/fastdlserver

**Comment by Glubbable** [comment]
No his head isn't suppose to be purple, that means something is failing to download or is missing from your server/fastdl and you should probably look into that.

And yes you can, via the profile packs.

**Comment by Draakoor** [comment]
There arent missing files i check it, i opend the newoverlay.vtf with vtfedit his face has purple things. Is that normal?

**Comment by Glubbable** [comment]
Yes that is normal, I thought you meant the actual model's face.
