### ISSUE TITLE
Crashing server.

### ISSUE THREAD

**Issue by Delfyy** [KitRifty/slender-fortress#12]
Hey! I have an trouble. When someone picked weapon from restrictedweapons, the server will crush right after round starts.
On my server no conflicting plugins. Just Slender Fortress 2 and all what it need.
How to fix this?
Also ive seen 0.2.7 version. How can i get it? maybe in it fix?

**Comment by Kenzzer** [comment]
I'm not sure it's directly related to sf2 itself, I was on your server when the crash happened. 
The new version 0.2.7 are done by me and can be found at this link: https://github.com/Benoist3012/Slender-Fortress-new-versions./releases.

It would be more easy for me to fix your crash if we are on the server, and you can send me error logs via steam.

My steam name is same on GitHub: Benoist3012, full steam name: -GoV- Benoist3012

Edit: Well in case you can't found on steam here the link: http://steamcommunity.com/id/Benoist3012/

**Comment by msburgess3200** [comment]
The issue sounds more like a configuration error, or a gamedata issue.
Check both of these, and please provide your error log(s) regarding this.

**Comment by Kenzzer** [comment]
Well it's not related to gamedata because I haven't updated it since 0.2.6v, and i odn't think it's the boss config, because when i was on the server they played one round.

**Comment by msburgess3200** [comment]
To better assist you, please provide your error log(s).

**Comment by Kenzzer** [comment]
Error logs will not really help Glubbable recommanded me to recommand you to install a crash extension support. I'm not looking evrytime and Git-Hub I think will be more quick if can join your passworded server, and provide logs and see what is wrong.
Edit: I was about to post the link but it's done.

**Comment by Glubbable** [comment]
Use Accelerator from Alliedmods, it'll provide you with a crash dump that'll accurately pinpoint the last call the server made before it crashed.

https://forums.alliedmods.net/showthread.php?t=146644

**Comment by Delfyy** [comment]
Alright, thanks to all of you ;)
I will put this on server and will post all logs here abit later

**Comment by Delfyy** [comment]
So, i put this on server. Whrere i can see the crush info?

**Comment by Glubbable** [comment]
Read the thread for instructions, it's basically a site that processes crash dumps into a readable format on their site. It'll basically show us was the very last thing that happened on the server before it crashed, it's way more reliable than any sourcemod logs or plugins list.

**Comment by Kenzzer** [comment]
Crash is now fixed.

**Comment by Delfyy** [comment]
Yeah, thanks to all :)
Problem was in outdated tf2items data.
