### ISSUE TITLE
Slender Fortress 1.0.0 crashes when a boss spawns

### ISSUE THREAD

**Issue by NicolasGoni** [KitRifty/slender-fortress#19]
Here is my sourcemod log sf2 log: L 12/20/2019 - 17:02:14: [sf2.smx] -------- Mapchange to slender_arizona_a5 -------
L 12/20/2019 - 17:02:16: [sf2.smx] Loading boss profiles from file addons\sourcemod\configs\sf2\profiles.cfg...
L 12/20/2019 - 17:02:16: [sf2.smx] slenderman...
L 12/20/2019 - 17:02:17: [sf2.smx] rake...
L 12/20/2019 - 17:02:17: [sf2.smx] weepingangel...
L 12/20/2019 - 17:02:17: [sf2.smx] Loaded 3 boss profile(s) from file!
L 12/20/2019 - 17:02:17: [sf2.smx] Reloaded restricted weapons configuration file successfully
L 12/20/2019 - 17:02:36: [sf2.smx] Player nicookapoo1 ([U:1:1000987864]) has mat_supportflashlight enabled, projected flashlight will be used
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:02:42: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 97 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 79 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 80 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:03:13: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:03:29: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 97 (Entity)!
L 12/20/2019 - 17:03:29: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 79 (Entity)!
L 12/20/2019 - 17:03:29: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple)  end touch by 80 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] Found sf2_maxplayers entity, set maxplayers to 8
L 12/20/2019 - 17:03:30: [sf2.smx] Found sf2_time_limit entity, set time limit to 240
L 12/20/2019 - 17:03:30: [sf2.smx] Found sf2_time_gain_from_page entity, set time gain to 10
L 12/20/2019 - 17:03:30: [sf2.smx] Found sf2_escape_time_limit entity, set escape time limit to 120
L 12/20/2019 - 17:03:30: [sf2.smx] Loaded page music ranges successfully!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 80 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 79 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:03:30: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 97 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger start touch by 94 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 97 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 97 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 79 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 79 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 80 (Entity)!
L 12/20/2019 - 17:03:34: [sf2.smx] [SF2 TRIGGERS LOG] Trigger 154 (trigger_multiple) sf2_pvp_trigger end touch by 80 (Entity)!
and my other log:
L 12/20/2019 - 17:01:42: SourceMod log file session started (file "C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\addons\sourcemod\logs\L20191220.log") (Version "1.10.0.6459")
L 12/20/2019 - 17:01:42: [TF2ITEMS] "GiveNamedItem" offset = 475
L 12/20/2019 - 17:02:13: [navmesh.smx] Couldn't find .nav file in maps folder, checking custom folders...
L 12/20/2019 - 17:02:13: [navmesh.smx] .NAV file for slender_arizona_a5 could not be found
L 12/20/2019 - 17:02:17: [sf2.smx] Loaded special rounds file!
L 12/20/2019 - 17:02:39: [randomcycle.smx] RandomCycle has chosen koth_badlands for the nextmap.
L 12/20/2019 - 17:04:00: [funcommands.smx] "Console<0><Console><Console>" toggled noclip on "nicookapoo1<2><[U:1:1000987864]><>"
L 12/20/2019 - 17:04:31: [sf2.smx] nicookapoo1 added a boss! (slenderman)

**Comment by Glubbable** [comment]
This version of SF2 is old, heavily outdated and not supported anymore. But there are newer versions from here that you can try. But keep in mind that SF2 no longer gets any form of public support anymore.

https://github.com/Kenzzer/Slender-Fortress-New-Versions
