### ISSUE TITLE
Problem with spawn sounds

### ISSUE THREAD

**Issue by Lykrast** [KitRifty/slender-fortress#4]
Well basically, after reinstalling all the thing and actually managing to make stuff work on a listen server, I have run into this issue where bosses don't seem to play their spawning sound. I know they don't all have one, but even when forcing a boss that has one (in this case it was SCP-049), still no intro sound. It doesn't seem to be related to the sound paths or something similar because all others sounds have the same path and play perfectly well. And upon looking in the code to search for what could be the name of the thing, I found it to be "sound_spawn_all", which is exactly what is configured into these profiles.

Could anyone help with this issue ?

**Comment by Lykrast** [comment]
Well after switching on another map, it seems the spawn sounds now work... that's really strange...

**Comment by Lykrast** [comment]
Well no, it isn't sadly resolved after a bit more testing, on some maps the sounds don't play, on some others they play at a low volume.

**Comment by Glubbable** [comment]
You're not suppose to be hosting any mods off of a listen server in TF2.

You'll have to get SRCD via the Valve's SteamCMD, which I've linked for you.
https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by Lykrast** [comment]
The basics of the mod seems to be working on this dedicated server, only problems being that it doesn't seem to load sounds, models (or at least Slenderman's, having tried with others) and overlays.
I have tried installing it the way I did for the listen server (putting the thing in the "custom" directories, and it worked there for the listen), then following what the guide did and putting the models and materials and sound directly in the "tf" directory of the server, but it isn't working as said previously.

**Comment by Glubbable** [comment]
What sourcemod build are you using? I'm currently running on the 1.6 branch still.

**Comment by Lykrast** [comment]
I was using the latest 1.7.0 version. Because I could not find the download for latest 1.6 version, I took the latest snapshot of it (1.6.4-git4625.zip).
It is still not loading those custom assets, but at least I can tell that Meem's model is loaded perfectly well.

I'm just gonna take this opportunity to slip in an unrelated question : are you planning on keeping to release once in a while more bosses to the public ?

**Comment by Glubbable** [comment]
Your question doesn't make sense, I cannot understand what you are asking about the bosses.

As for this current issue, it sounds like your server is failing to load the complete configs due to there being to much stuff to load within the small timeframe that is allowed for script loading or your server is to slow at loading stuff and therefore will be timed out to prevent a server hang.

I really don't know whats wrong and there's nothing we can do i'm affraid.

**Comment by Lykrast** [comment]
Well that seems really sad... thanks you for trying to help me, but I guess I'll just continue on the buggy listen server for now...

That question was about the fact you put some bosses on public download for server hosts (most recent was the FNAF2 "gang"), and it was asking you if you would continue to do that in the future (even at a slow rate).
