### ISSUE TITLE
problem with spawn boss and animations bosses

### ISSUE THREAD

**Issue by DarkSny** [KitRifty/slender-fortress#5]
Hello I have a problem with spawn boss and animations for bosses I looked into the FAQ but nothing was written there not helped me.

Dynamic prop prop_dynamic: no sequence named:walk_all
Dynamic prop prop_dynamic: no sequence named:idle01
Dynamic prop prop_dynamic: no sequence named:Run
Dynamic prop prop_dynamic: no sequence named:BR2_Attack
Dynamic prop prop_dynamic: no sequence named:BR2_Roar

In other bosses I completely same problem.

I have a problem with DHooks:
sf2.sp
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<91> : error 139: could not find type "typeset"
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<94> : error 010: invalid function or declaration
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<144> : error 054: unmatched closing brace <"}">
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<153> : error 139: could not find type "ListenCB"
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<174> : error 139: could not find type "DHookCallback"
F:\Slender Fortress 2 Server\server\tf\addons\sourcemod\scripting\include\dhooks.inc<199> : error 139: could not find type "DHookRemovalCB"

NAV. I have files in the folder maps, and the same bosses not spawn

**Comment by Walter20210** [comment]
Do you use the latest snapshot of Sourcemod? Because the version 1.7.2 has certain issues with the current update.

Also are the needed plugins updated too?

**Comment by DarkSny** [comment]
I used TFItems 1.6.2 Sourcemod 1.6.3 Steamtools 0.9.1

**Comment by Walter20210** [comment]
Oh, your Sourcemod seems to be outdated, you should update it to the latest snapshot.

You can get it from here:
http://www.sourcemod.net/snapshots.php

**Comment by DarkSny** [comment]
DHooks I do not have a problem but I have a problem with something else.

I still have a problem with animation boss while he may run into attacking other players, but it has no animation

Dynamic prop prop_dynamic: no sequence named:walk_all
Dynamic prop prop_dynamic: no sequence named:idle01
Dynamic prop prop_dynamic: no sequence named:Run
Dynamic prop prop_dynamic: no sequence named:BR2_Attack
Dynamic prop prop_dynamic: no sequence named:BR2_Roar

sf2.sp

sf2/profiles/profile_chaser.sp<236> : warning 203: symbol is never used: "sBuffer"
sf2/client.sp<107> : error 122: expected type expression
sf2/client.sp<109> : error 166: cannot use ´this´ outside of a methodmap method or property
sf2/client.sp<3475> : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
sf2.sp<6375> : warning 203: symbol is never used: "DidClientPlayNewBossRound"
sf2.sp<6375> : warning 203: symbol is never used: "DidClientPlaySpecialRound"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserGetAttackDuration"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserGetAttackType"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserGetMaxAirSpeed"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserGetMovementActivity"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetState"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetWalkSpeed"
sf2.sp<6375> : warning 203: symbol is never used: "NPCGetEnemy"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserGetState"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetAirSpeed"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetMaxAirSpeed"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetMaxWalkSpeed"
sf2.sp<6375> : warning 203: symbol is never used: "NPCChaserSetMovementActivity"

Boss already spawns but not animations.

**Comment by Walter20210** [comment]
It says the animation is not found in the model according to:

"Dynamic prop prop_dynamic: no sequence named:walk_all"

Try to make sure the animation is named in the same way as, the animation you set it for the boss on its profile.

You can easily check it using HLMV, and opening your model and the look for the sequences/animations names.

**Comment by Glubbable** [comment]
Please make sure that the models are actually in the main tf directory, if its in custom or download then the server will not be able to load the assets.

Also, please update sourcemod on your server as 1.6 is no longer supported and the current latest verion is 1.7.3 at this current time.

**Comment by DarkSny** [comment]
I installed sourcemod 1.7.3 I still have a problem with animations.

**Comment by Glubbable** [comment]
When installing the SF2 resources, did you upload the required files to the main tf directory of the server?

**Comment by DarkSny** [comment]
yes I installed everything into tf folder server.

**Comment by Glubbable** [comment]
Could you check if the rake model is in the models directory.

**Comment by DarkSny** [comment]
yes all models are in the folder models / slender

**Comment by DarkSny** [comment]
I looked at the names of animations in HLMW and when I entered the animation to the boss correctly thus as well not have any animations.

**Comment by DarkSny** [comment]
I reinstalled my server and animations are already just fine I'm sorry if I annoying.
